###############################################################################
# Taps
###############################################################################
# No taps right now!

###############################################################################
# Binaries
###############################################################################
# Shell stuff
brew 'antigen'
brew 'autojump'
brew 'bat'
brew 'coreutils'
brew 'fzf'
brew 'gnu-sed'
brew 'gnutls'
brew 'grpcurl'
brew 'htop'
brew 'jq'
brew 'rclone'
brew 'readline'
brew 'rsync'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh'

# Dev things
brew 'cookiecutter'
brew 'diff-so-fancy'
brew 'ffmpeg'
brew 'imagemagick'
brew 'jenv'
