###############################################################################
# Taps
###############################################################################

# zsh things
tap 'sambadevi/powerlevel9k'

# Dev things
tap 'jesseduffield/lazygit'

###############################################################################
# Binaries
###############################################################################
# Shell stuff
brew 'zsh'
brew 'powerlevel9k'
brew 'antigen'
brew 'fzf'
brew 'gnu-sed'
brew 'htop'
brew 'jq'
brew 'rsync'
brew 'readline'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'autojump'
brew 'lazygit'
brew 'bat'

# Dev things
brew 'imagemagick'
brew 'cookiecutter'
brew 'jenv'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'diff-so-fancy'
brew 'rclone'
