#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

# Determine what machine we're on
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine="Linux";;
    Darwin*)    machine="Mac";;
    *)          machine="UNKNOWN:${unameOut}"
esac

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

check_brew_installed () {
  # Install brew dependencies
  if [ -z $(which brew) ]; then
    fail "Brew installation not found.  Please install brew and re-run the bootstrapper. \n    To install brew, see https://brew.sh/"
  fi
}

setup_gitconfig () {
  if ! [ -f symlinks/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" symlinks/gitconfig.symlink.example > symlinks/gitconfig.symlink

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

create_templates () {
  info 'creating files'

  if [ ! -f ~/.bash_custom ]; then
      cat << EOF >> ~/.bash_custom
#!/usr/bin/env bash

# Machine-specific bash commands here

EOF
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  # TODO: Finish this up
  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

run_installers () {
  source $DOTFILES_ROOT/script/run_installers
}

install_fonts () {
  MAC_FONTS_ROOT=/Library/Fonts

  # Copy all the fonts
  for f in $DOTFILES_ROOT/fonts/*.ttf; do
    fname=$(basename $f)
    if [[ "$machine" == "Mac" ]] && [[ ! -f "$MAC_FONTS_ROOT/$fname" ]]; then
      cp "$f" "$MAC_FONTS_ROOT"
    fi
  done
}

# Call all the functions defined above
check_brew_installed
setup_gitconfig
create_templates
install_dotfiles
run_installers
install_fonts

echo ''
echo '  All installed!'
echo '  You may need to restart your terminal for the changes to take effect.'
